name: my_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  equatable: ^2.0.3
  logger: ^1.1.0
  http: ^0.13.4
  device_info_plus: ^3.2.4
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2
  environment_config: ^3.1.0
  url_launcher: ^6.1.3
  formz: ^0.4.1
  
  # WIDGET
  modal_bottom_sheet: ^2.0.1
  bot_toast: ^4.0.2
  flutter_svg: ^1.1.0
  shimmer: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_slidable: ^1.3.0
  # fluttertoast: ^8.0.9
  
  # STATE MANAGEMENT
  flutter_bloc: ^8.0.1
  auto_route: ^4.0.1

  # FIREBASE
  # GITHUB

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/images/
    - assets/images/locale/
